### PR TITLE
Document encoded data formats and other updates

### PR DESCRIPTION
**Pull request by gipert**
Work in progress.

### CODE REVIEW

**Comment by oschulz** [comment]
Thanks a lot, @gipert !

**Comment by gipert** [comment]
Hi @oschulz, could you have a look at this? I'm not sure about the overall structure.

Also, should we move web pages deployment to GitHub Actions, and enable multiple versions?

https://documenter.juliadocs.org/stable/man/hosting/#GitHub-Actions

**Comment by gipert** [comment]
@oschulz I'm afraid I have to ping you on this... could you review and configure the GitHub actions workflows? If you know how to do it, could you also configure multi-version builds? Thanks

**Comment by oschulz** [comment]
Thanks for the reminder, will do!

Regarding multi-version builds, I think it's actually best if the format documentation is not versioned itself - instead, the current stats of this documentation should always describe all versions of the formats we use (since people may need to read older files).

**Comment by gipert** [comment]
Ok, but we should still version the specification and store the version in the LH5 files, in my opinion.

**Comment by oschulz** [comment]
> Ok, but we should still version the specification and store the version in the LH5 files, in my opinion.

Yes, we should certainly version the spec, and store it version in the files. I think it's better to keep the versions together in the documentation, though. The differences will (hopefully) mostly be minor, so it's probably best to have one documenter and then "v1.0: .... v1.1: ...." in some sections. This will also help people who want to implement cross-version support.

**Comment by oschulz** [comment]
> Also, should we move web pages deployment to GitHub Actions

Doing this now in #4

**Comment by oschulz** [comment]
@gipert, can you rebase this on main?

Sorry for the conflicts, had to change a few things to fix docgen.

**Comment by gipert** [comment]
Done!

**Comment by gipert** [comment]
@oschulz this is ready to merge from my point of view... Could you have a look?

**Comment by oschulz** [comment]
Looks great to me, thanks a lot Luigi!

In the future, we could think about deprecating long datatype names like `array_of_equalsized_encoded_arrays` in favor of more structured names like `array_of_equalsized<n>{encoded_array<m>}}` or so. That would allow us to allows nested equal-sized arrays and so on.

**Pull request merged**
